<?php
declare(strict_types=1);

// RedTideInformation SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

RedTideInformationUtility::setRegistrar(function (RedTideInformationUtility $u): void {
    $u->clean = [RedTideInformationClean::class, 'call'];
    $u->done = [RedTideInformationDone::class, 'call'];
    $u->make_error = [RedTideInformationMakeError::class, 'call'];
    $u->feature_add = [RedTideInformationFeatureAdd::class, 'call'];
    $u->feature_hook = [RedTideInformationFeatureHook::class, 'call'];
    $u->feature_init = [RedTideInformationFeatureInit::class, 'call'];
    $u->fetcher = [RedTideInformationFetcher::class, 'call'];
    $u->make_fetch_def = [RedTideInformationMakeFetchDef::class, 'call'];
    $u->make_context = [RedTideInformationMakeContext::class, 'call'];
    $u->make_options = [RedTideInformationMakeOptions::class, 'call'];
    $u->make_request = [RedTideInformationMakeRequest::class, 'call'];
    $u->make_response = [RedTideInformationMakeResponse::class, 'call'];
    $u->make_result = [RedTideInformationMakeResult::class, 'call'];
    $u->make_point = [RedTideInformationMakePoint::class, 'call'];
    $u->make_spec = [RedTideInformationMakeSpec::class, 'call'];
    $u->make_url = [RedTideInformationMakeUrl::class, 'call'];
    $u->param = [RedTideInformationParam::class, 'call'];
    $u->prepare_auth = [RedTideInformationPrepareAuth::class, 'call'];
    $u->prepare_body = [RedTideInformationPrepareBody::class, 'call'];
    $u->prepare_headers = [RedTideInformationPrepareHeaders::class, 'call'];
    $u->prepare_method = [RedTideInformationPrepareMethod::class, 'call'];
    $u->prepare_params = [RedTideInformationPrepareParams::class, 'call'];
    $u->prepare_path = [RedTideInformationPreparePath::class, 'call'];
    $u->prepare_query = [RedTideInformationPrepareQuery::class, 'call'];
    $u->graphql_body = [RedTideInformationGraphql::class, 'body'];
    $u->graphql_errors = [RedTideInformationGraphql::class, 'errors'];
    $u->result_basic = [RedTideInformationResultBasic::class, 'call'];
    $u->result_body = [RedTideInformationResultBody::class, 'call'];
    $u->result_headers = [RedTideInformationResultHeaders::class, 'call'];
    $u->transform_request = [RedTideInformationTransformRequest::class, 'call'];
    $u->transform_response = [RedTideInformationTransformResponse::class, 'call'];
});
